### ISSUE TITLE
Custom styling for nodes and function buttons

### ISSUE THREAD

**Issue by inequity** [MagForceSeven/UE-K2-Nodes#1]
Hello!

Do you have any idea how the K2Node_SwitchString and K2Node_SwitchInteger nodes have the 'Add pin' button on the node, or how the Default pin is below a separator and the other pins are rendered above it? Where is this kind of styling being done?

Thanks!

**Comment by MagForceSeven** [comment]
The short answer is Slate.

Both of those nodes are children of K2Node_Switch which has a custom Slate widget for rendering the node. There's then some annoyingly specific engine code that chooses a slate widget for the node based on it's type. Annoying because you can't easily extend it without adding your node to the engine.

The good news is there is also a function you can override from EdGraphNode (the parent of K2Node) named CreateVisualWidget which allows you to return a custom SGraphNode that can be used to display your node. I have not done a whole lot in this area yet. I've only really created one custom SGraphNode and it was mostly copy/paste from an engine node. But if you bounce around the source a little bit you should be able to fine the Slate widget for switch nodes to see what it's doing.
